name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install Gauge
        run: |
          curl -sL https://downloads.gauge.org/stable | sh
          gauge --version

      - name: Install Gauge Plugin
         run: |
           gauge install go
           gauge install html-report
           gauge install xml-report

      - name: Run tests
        run: gauge run --verbose specs/versions.spec

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
